# Generated by Django 3.1.4 on 2021-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210309_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
