# Generated by Django 3.1.4 on 2021-03-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210307_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='course_name',
        ),
    ]
